## Author

**Name:** Ibtisaam Javid Dalvi

**Email:** **idalvi2@illinois.edu**

## Post Feedback Changes

1. Removed repetitive line of code that originally reread everything from Spotify. This greatly improve speed of album filtration.
2. Removed the Compare Insights tab because not very helpful and did not add to the user experience.

## Purpose

The purpose of the application is to look at particular aspects of your favorite artists' music through some of Spotify's insights: valence, danceability and energy! We have shown a plot and a table of data to-date at time of selection.

Users can learn about any artists' discography through the search bar and even filter for a specific album with the second search bar if they so choose. All selections will be  made on the first page while the tabs at the top of the app will allow users to browse between the different types of insights. Be patient as it may take some time for selections to load.

Each insight page will display its respective plot, range (where you can hover to get specific values), and table. The last page lets users look at relationship between certain insights.

## As  Defined by Spotify

**Valence**:
“A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).”

**Danceability:**
“Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.”

**Energy:**
“Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.”

## Data

The data sourced from Spotify's API that is up-to-date. 